name: Auto-Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Dependabot PR
        id: dependabot
        run: echo "::set-output name=is-dependabot::$(if [[ '${{ github.actor }}' == 'dependabot[bot]' ]]; then echo true; else echo false; fi)"

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Labels
        run: |
          labels=$(gh pr view "${{ github.event.pull_request.number }}" --json labels --jq '.labels[].name')
          echo "Labels: $labels"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge if Dependabot and tests pass
        if: steps.dependabot.outputs.is-dependabot == 'true' && steps.check_label.outputs.has-dependencies-label == 'true'
        run: gh pr merge ${{ github.event.pull_request.number }} --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}